[build]
  publish = "out"
  command = "npm run build"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "22"

# Next.js configuration for serverless with Firebase
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Headers for Firebase Auth
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Redirects for SPA behavior - correct syntax for static export
[[redirects]]
  from = "/dashboard"
  to = "/dashboard/index.html"
  status = 200

[[redirects]]
  from = "/simulation"
  to = "/simulation/index.html"
  status = 200

[[redirects]]
  from = "/documentation"
  to = "/documentation/index.html"
  status = 200

# Fallback redirect for any unmatched routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
